carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home, checkout_done_view

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),

    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]
app_name = 'cart'

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include("carts.urls", namespace='cart')),
    # auth start here
    path('register/', register_page, name='register'),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/guest/', guest_register_view, name='guest_register'),
    # auth end here
    path('checkout/address/create/', checkout_address_create_view,
         name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view,
         name='checkout_address_reuse'),
    url('api/cart/', cart_detail_api_view, name='api-cart'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product
User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        # getter function to get the cart id from the session
        cart_id = request.session.get("cart_id", None)
        # get the id from the database
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            # if it is exist then we set the same cart_obj variable to qs
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                # if user logged in then change the previous "None" user to authenticated one
                cart_obj.user = request.user
                cart_obj.save()
        else:
            # create a brand new cart
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            # setter function to set the cart id to the session
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        # if the user isn"t logged in then create a new session for None user
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                # if the user is logged in then create a new session for logged in user
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    """ print(action)
    print(instance.products.all())
    # pre_remove =before removing the item what were in the dictionary
    # post_remove =after removing the item what are in the dictionary
    # post_add =before adding the item what were in the dictionary
    # post_remove =after adding the item what are in the dictionary """
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        # instance here is the cart_obj
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal + 10
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

# For order App start here
from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address
from billing.models import BillingProfile
from orders.models import Order
# For order App end here

from products.models import Product
from .models import Cart


def cart_home(request):
    # print(request.session)
    # print(request.session.session_key) #output: inn3oycr35dkxqg81lz7a2lkz23vktnx
    # request.session.set_expiry(300) # 5 minutes
    """ request.session['first_name'] = "Sumnan" #setter(can't set object)
    print(request.session.get("first_name", "Unknown")) #getter """

    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    # get the product id from update-cart form name "product_id"
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            # grab the product
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("wrong product_id")
            return redirect("cart:home")
        # grab the current instance or, create a new one
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
            # stay in the product page
            # return redirect(product_obj.get_absolute_url())
        else:
            # add the product itself into the instances many to many field(in this case product field).
            cart_obj.products.add(product_obj)
            added = True
        # get the total Item
        request.session['cart_items'] = cart_obj.products.count()

        # For ajaxifying add to cart
        if request.is_ajax():
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount": cart_obj.products.count()
            }
            return JsonResponse(json_data, status=200)  # HttpResponse
            # return JsonResponse({"message": "Error 400"}, status=400) # Django Rest Framework

    return redirect("cart:home")


# refresh the cart using ajax
def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
        "id": x.id,
        "url": x.get_absolute_url(),
        "name": x.title,
        "price": x.price
    } for x in cart_obj.products.all()]
    cart_data = {
        "products": products,
        "subtotal": cart_obj.subtotal,
        "total": cart_obj.total
    }
    return JsonResponse(cart_data, status=200)


# order app (checkout)
def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(
        request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(
                billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(
                id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(
                id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }
    return render(request, "carts/checkout.html", context)


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}
<div class='col-6 mx-auto py-5 text-center'>
  <h1 class='display-1'>Thank you for your order!!!</h1>
</div>
{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

{% if not billing_profile %}
    <div class='row text-center'>
    <div class='col-12 col-md-6'>
        <p class='lead'>Login</p>
        <!-- build_absolute_uri = Returns the absolute URI form of location.  -->
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class='col-12 col-md-6'> 
        Continue as Guest
        {% url "guest_register" as guest_register_url %}
        {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
    </div>
    </div>
{% else %}  
    {% if not object.shipping_address %}
        <div class='row'>
        <div class='col-12'>
            <p class='lead'>Shipping Address</p>
            <hr/>
        </div>
        <div class='col-6'>
            {% url "checkout_address_create" as checkout_address_create %}
            {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}'
        </div>
        <div class='col-6'>
        {% url 'checkout_address_reuse' as checkout_address_reuse %}
        {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
        </div>
    </div>
    {% elif not object.billing_address %}
    <div class='row'>
        <div class='col-12'>
            <p class='lead'>Billing Address</p>
            <hr/>
        </div>
        <div class='col-6'>
        {% url "checkout_address_create" as checkout_address_create %}
        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
        </div>
            <div class='col-6'>
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
        </div>
    </div>
    {% else %}
        <h1>Finalize Checkout</h1>
        <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        <p>Shipping Address: {{ object.shipping_address.get_address }}</p>
        <p>Billing Address: {{ object.shipping_address.get_address }}</p>
        <p>Cart Total: {{ object.cart.total }}</p>
        <p>Shipping Total: {{ object.shipping_total }}</p>
        <p>Order Total: {{ object.total }}</p>
        <form class='form' method='POST' action="">{% csrf_token %}
            <button type='submit' class='btn btn-success'>Checkout</button>
        </form>
    {% endif %}
{% endif %}

{% endblock %}

carts/templates/carts/home.html
{% extends "base.html" %}


{% block content %}
<h1>Cart</h1>

{% if cart.products.exists %}
<table class="table cart-table">
  <thead>
    <tr>
      <th>#</th>
      <th>Product Name</th>
      <th>Product Price</th>
    </tr>
  </thead>
  <tbody class='cart-body'>
    {% for product in cart.products.all %}
    <tr class='cart-product'>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href='{{ product.get_absolute_url }}'>{{ product.title }}</a> 
        {% include 'carts/snippets/remove-product.html' with product_id=product.id %}
      </td>
      <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
    <tr>
      <td colspan="2"></td>
      <td><b>Subtotal</b> $<span class='cart-subtotal'>{{ cart.subtotal }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><b>Total</b> $<span class='cart-total'>{{ cart.total }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><a class='btn btn-lg btn-success' href='{% url "cart:checkout" %}'>Checkout</a></td>
    </tr>

  </tbody>
</table>

<div class='cart-item-remove-form' style='display:none'>
  {% include 'carts/snippets/remove-product.html' %}
</div>

{% else %}
  <p class='lead'>Cart is empty</p>
{% endif %}


{% endblock %}