carts/urls.py
from django.conf.urls import url

from .views import cart_home, cart_update, checkout_home, checkout_done_view

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),

    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
]
app_name = 'cart'

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page, guest_register_view

from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('search/', include("search.urls", namespace='search')),
    path('cart/', include("carts.urls", namespace='cart')),
    # auth start here
    path('register/', register_page, name='register'),
    path('login/', login_page, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/guest/', guest_register_view, name='guest_register'),
    # auth end here
    path('checkout/address/create/', checkout_address_create_view,
         name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view,
         name='checkout_address_reuse'),
    url('api/cart/', cart_detail_api_view, name='api-cart'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from .views import (
    ProductListView,
    product_list_view,
    ProductDetailView,
    product_detail_view,
    ProductFeaturedListView,
    ProductFeaturedDetailView,
    ProductDetailSlugView
)
urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    # http://127.0.0.1:8000/products-fbv/
    url(r'^products-fbv/$', product_list_view),
    url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # http://127.0.0.1:8000/products-fbv/1
    url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
    url(r'^featured/$', ProductFeaturedListView.as_view()),
    url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    url(r'^products/(?P<slug>[\w-]+)/$',
        ProductDetailSlugView.as_view(), name='detail'),
]
app_name = 'products'

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href='{% static "bootstrap/bootstrap.min.css" %}'>
    <link rel='stylesheet' href='{% static "css/main.css" %}'>

    <title>An E-Commerce Site</title>
  </head>
  <body>
    <div class='container'>
        {% include 'navbar.html' with brand_name='Django E-Commerce' %}
        {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src='{% static "bootstrap/jquery-3.5.1.min.js" %}'></script>
    <script src='{% static "bootstrap/popper.min.js" %}'></script>
    <script src='{% static "bootstrap/bootstrap.min.js" %}'></script>
    <script src='{% static "js/csrf.ajax.js" %}'></script>
    <script src='{% static "js/ecommerce.js" %}'></script>
  </body>
</html>

templates/navbar.html
{% load static %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ product_list_url }}">
        {% if brand_name %} {{brand_name }} {% else %}CFE eCommerce {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ product_list_url }}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path == logout_url %}active{% endif %} ">
            <a class="nav-link" href="{{ logout_url }}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item {% if request.path == register_url %}active{% endif %}">
            <a class="nav-link" href="{{ register_url }}">Register</a>
          </li>
          <li class="nav-item {% if request.path == login_url %}active{% endif %}">
            <a class="nav-link" href="{{ login_url }}">Login</a>
          </li>
        {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span><i>Cart</i></a>
        </li>  

        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> -->
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </nav>